PUT http://localhost:3001/trains/12/location
Content-Type: application/json; charset=utf-8

{
    "name" : "testijuna",
    "destination" : "hellsinki",
    "speed" : 200.0,
    "coordinates" : [60.66, 25.55]
}